name: Deploy to EC2 (Staging) — authVUE

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"
      deploy_backend:
        description: "Deploy backend?"
        type: boolean
        default: true
      deploy_frontend:
        description: "Deploy frontend?"
        type: boolean
        default: true

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: staging
      url: ${{ vars.FRONTEND_URL }}

    steps:
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Sanity check (SSH)
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'echo HOME=$HOME; hostname; uname -a'

      # Herramientas + clonar si falta + actualizar rama
      - name: Bootstrap EC2 (tools + clone/update)
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -euo pipefail
          REPO_URL="https://github.com/${{ github.repository }}.git"
          REPO_NAME="$(basename -s .git "$REPO_URL")"
          APP_DIR="$HOME/$REPO_NAME"
          BRANCH="${{ github.event.inputs.branch }}"

          # herramientas base (idempotente)
          if ! command -v git  >/dev/null 2>&1; then sudo apt update && sudo apt install -y git; fi
          if ! command -v node >/dev/null 2>&1; then curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt install -y nodejs; fi
          if ! command -v pm2  >/dev/null 2>&1; then sudo npm i -g pm2; fi
          if ! command -v nginx >/dev/null 2>&1; then sudo apt install -y nginx; fi

          # clonar si falta
          if [ ! -d "$APP_DIR/.git" ]; then
            cd "$HOME"
            git clone "$REPO_URL"
          fi

          # dejar la rama limpia y actualizada
          cd "$APP_DIR"
          git fetch origin "$BRANCH" || true
          git checkout "$BRANCH" || git checkout -B "$BRANCH" "origin/$BRANCH"
          git reset --hard "origin/$BRANCH"
          git clean -fdx
          EOF

      # .env del backend (escribe directamente en la EC2)
      - name: Write backend .env on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'REPO_URL="https://github.com/${{ github.repository }}.git"; \
             APP_DIR="$HOME/$(basename -s .git "$REPO_URL")"; \
             mkdir -p "$APP_DIR/backend"; \
             cat > "$APP_DIR/backend/.env" << "ENVEOF"
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL=${{ vars.GOOGLE_CALLBACK_URL }}
          FRONTEND_URL=${{ vars.FRONTEND_URL }}
          PORT=${{ vars.PORT }}
          JWT_EXPIRES=${{ vars.JWT_EXPIRES }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          ENVEOF'

      # BACKEND: deps (prod) + PM2
      - name: Deploy BACKEND
        if: ${{ github.event.inputs.deploy_backend == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -euo pipefail
          REPO_URL="https://github.com/${{ github.repository }}.git"
          APP_DIR="$HOME/$(basename -s .git "$REPO_URL")"
          cd "$APP_DIR/backend"

          # instala sólo dep. de runtime (si tu backend NO compila TS aquí)
          npm ci --omit=dev || npm install --omit=dev
          # si necesitas compilar TS, usa: npm ci && npm run build

          pm2 restart backend || pm2 start npm --name backend -- start
          pm2 save
          EOF

      # FRONTEND: build + publicar en NGINX
      - name: Deploy FRONTEND
        if: ${{ github.event.inputs.deploy_frontend == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -euo pipefail
          REPO_URL="https://github.com/${{ github.repository }}.git"
          APP_DIR="$HOME/$(basename -s .git "$REPO_URL")"
          BRANCH="${{ github.event.inputs.branch }}"

          # checkout limpio (evita residuos como index.js antiguos)
          cd "$APP_DIR"
          git fetch origin "$BRANCH" || true
          git checkout "$BRANCH" || git checkout -B "$BRANCH" "origin/$BRANCH"
          git reset --hard "origin/$BRANCH"
          git clean -fdx

          # build
          cd "$APP_DIR/frontend"
          npm ci --no-audit --fund=false
          # si tienes script "build-only" sin vue-tsc, úsalo; si no, build normal
          if npm run | grep -q "build-only"; then
            npm run build-only
          else
            npm run build
          fi

          # publicar
          sudo rm -rf /var/www/html/*
          sudo rsync -av --delete dist/ /var/www/html/
          sudo nginx -t
          sudo systemctl reload nginx || sudo systemctl restart nginx
          EOF

      - name: Smoke check
        run: |
          curl -I --max-time 15 ${{ vars.FRONTEND_URL }} || true
