name: build-test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug layout
        run: |
          pwd
          ls -la
          ls -la backend | grep package-lock || true

      - name: Use Node.js 22.15
        uses: actions/setup-node@v4
        with:
          node-version: "22.15"
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install (backend)
        working-directory: backend
        run: npm ci

      - name: Test (backend)
        working-directory: backend
        run: npm test -- --ci --runInBand
